# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: serving.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='serving.proto',
  package='widedeep.serving',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rserving.proto\x12\x10widedeep.serving\"(\n\x06Matrix\x12\x0f\n\x07outputs\x18\x01 \x03(\x02\x12\r\n\x05shape\x18\x02 \x03(\x05\"4\n\nPredictReq\x12&\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x18.widedeep.serving.Matrix\"5\n\x0bPredictResp\x12&\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x18.widedeep.serving.Matrix2]\n\x11MatrixSlowServing\x12H\n\x07Predict\x12\x1c.widedeep.serving.PredictReq\x1a\x1d.widedeep.serving.PredictResp\"\x00\x62\x06proto3')
)




_MATRIX = _descriptor.Descriptor(
  name='Matrix',
  full_name='widedeep.serving.Matrix',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='outputs', full_name='widedeep.serving.Matrix.outputs', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shape', full_name='widedeep.serving.Matrix.shape', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=75,
)


_PREDICTREQ = _descriptor.Descriptor(
  name='PredictReq',
  full_name='widedeep.serving.PredictReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='widedeep.serving.PredictReq.data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=129,
)


_PREDICTRESP = _descriptor.Descriptor(
  name='PredictResp',
  full_name='widedeep.serving.PredictResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='widedeep.serving.PredictResp.data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=131,
  serialized_end=184,
)

_PREDICTREQ.fields_by_name['data'].message_type = _MATRIX
_PREDICTRESP.fields_by_name['data'].message_type = _MATRIX
DESCRIPTOR.message_types_by_name['Matrix'] = _MATRIX
DESCRIPTOR.message_types_by_name['PredictReq'] = _PREDICTREQ
DESCRIPTOR.message_types_by_name['PredictResp'] = _PREDICTRESP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Matrix = _reflection.GeneratedProtocolMessageType('Matrix', (_message.Message,), dict(
  DESCRIPTOR = _MATRIX,
  __module__ = 'serving_pb2'
  # @@protoc_insertion_point(class_scope:widedeep.serving.Matrix)
  ))
_sym_db.RegisterMessage(Matrix)

PredictReq = _reflection.GeneratedProtocolMessageType('PredictReq', (_message.Message,), dict(
  DESCRIPTOR = _PREDICTREQ,
  __module__ = 'serving_pb2'
  # @@protoc_insertion_point(class_scope:widedeep.serving.PredictReq)
  ))
_sym_db.RegisterMessage(PredictReq)

PredictResp = _reflection.GeneratedProtocolMessageType('PredictResp', (_message.Message,), dict(
  DESCRIPTOR = _PREDICTRESP,
  __module__ = 'serving_pb2'
  # @@protoc_insertion_point(class_scope:widedeep.serving.PredictResp)
  ))
_sym_db.RegisterMessage(PredictResp)



_MATRIXSLOWSERVING = _descriptor.ServiceDescriptor(
  name='MatrixSlowServing',
  full_name='widedeep.serving.MatrixSlowServing',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=186,
  serialized_end=279,
  methods=[
  _descriptor.MethodDescriptor(
    name='Predict',
    full_name='widedeep.serving.MatrixSlowServing.Predict',
    index=0,
    containing_service=None,
    input_type=_PREDICTREQ,
    output_type=_PREDICTRESP,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MATRIXSLOWSERVING)

DESCRIPTOR.services_by_name['MatrixSlowServing'] = _MATRIXSLOWSERVING

# @@protoc_insertion_point(module_scope)
